[env]
TERM = "xterm-256color"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 160
lines = 64

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[general]
import = [
    "~/.config/alacritty/gruvbox.toml"
]

[terminal]
